feat: adding the experience decisioning plugin to handle experiments, audiences and campaigns
hlxsites/wknd pull request #31
Opened 2023-09-14 19:52 UTC by ramboz

Replacing the initial experimentation engine with the newer experience decisioning plugin for Franklin.

The plugin is the more mature version of the initial engine and follows the same APIs and authoring experience.
See: https://github.com/adobe/franklin-experience-decisioning/

Test URLs:
- Before: https://main--wknd--hlxsites.hlx.page/
- After: https://experience-decisioning--wknd--hlxsites.hlx.page/

2023-09-28 10:06 UTC, iuliag requested changes
Code LGTM and comments below are mostly referring to the experience decisioning plugin itself, not on how it's applied to this repo.
But... there's something buggy with the CSS that needs to be solved:
<img width="1787" alt="experiment-decisioning-overlay" src="https://github.com/hlxsites/wknd/assets/5692662/2409871c-5b78-4849-8061-df5ea89d9e9a">

2023-09-28 10:10 UTC, iuliag commented on plugins/experience-decisioning/README.md
> +- [Audiences](../../wiki/Audiences)
It would make sense to use absolute paths in the plugin, because these links return 404 in all repos where the plugin is installed.

2023-10-03 08:07 UTC, ramboz commented on scripts/scripts.js
> +    && (window.location.hostname === 'localhost' || window.location.hostname.endsWith('.hlx.page'))) {
Agreed, and I have it on my todo list to propose it in the boilerplate. But starting with baby steps first 😉

2023-10-03 08:08 UTC, ramboz commented on scripts/scripts.js
> +    const { loadLazy: runLazy } = await import('../plugins/experience-decisioning/src/index.js');
The idea is to align with the default page load phases from the boilerplate, which are called `load*`. For now I rename it locally to `runLazy` for lining reasons, but once we have the plugin system in the boilerplate, the instrumentation will be transparent… so it's just temporary

2023-10-03 08:08 UTC, ramboz commented on plugins/experience-decisioning/src/index.js
> +    return null;
Good point

2023-10-03 08:21 UTC, ramboz commented
@iuliag Yes, the CSS is a bit of a mess… the site styles are leaking quite a bit in the pill. They are a tad too generic.
We'll need to either manually set all CSS props on the pill to limit conflicts, or ideally, we should rewrite as a web component with isolated shadow DOM… but I think that will warrant a full separate PR

2023-10-05 09:11 UTC, ramboz commented
@iuliag let me know if you still have any concerns

2023-10-06 10:11 UTC, iuliag approved these changes

2023-10-30 07:56 UTC, merged